# yaml-language-server: $schema=https://raw.githubusercontent.com/cuioss/cuioss-organization/main/.github/actions/read-project-config/schema.json
name: cui-java-module-template
description: Template for cuioss Java modules

release:
  current-version: 1.0.0
  next-version: 1.1.0-SNAPSHOT
  create-github-release: true

maven-build:
  java-versions: '["21","25"]'
  java-version: '21'
  enable-snapshot-deploy: true
  maven-profiles-snapshot: 'release-snapshot,javadoc'
  maven-profiles-release: 'release,javadoc'
  npm-cache: false

sonar:
  project-key: cuioss_cui-java-module-template
  enabled: true
  skip-on-dependabot: true

pages:
  reference: cui-java-module-template
  deploy-at-release: true
